# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P3ziW2xk49uTRsrWtqG6oxzFLjKi1aDS
"""

!pip install google-play-scraper

from google_play_scraper import Sort, reviews
import pandas as pd

# 1. Menentukan ID aplikasi (bisa dilihat di URL Play Store)
app_id = 'id.dana'

# 2. Proses Scraping
result, continuation_token = reviews(
    app_id,
    lang='id',        # Bahasa Indonesia
    country='id',     # Wilayah Indonesia
    sort=Sort.NEWEST, # Ambil ulasan terbaru
    count=11000       # Target minimal 10.000 (kita ambil 11rb untuk cadangan)
)

# 3. Konversi ke Pandas DataFrame
df = pd.DataFrame(result)

# 4. Filter kolom yang dibutuhkan saja
df = df[['content', 'score', 'at']]

# 5. Tampilkan 5 data teratas
print(f"Total data yang berhasil diambil: {len(df)}")
df.head()

def pelabelan(score):
  if score <= 2:
    return 'Negatif'
  elif score == 3:
    return 'Netral'
  else:
    return 'Positif'

df['label'] = df['score'].apply(pelabelan)

# Cek distribusi kelas
print(df['label'].value_counts())

df.to_csv('dataset_ulasan_dana.csv', index=False)
print("File berhasil disimpan sebagai dataset_ulasan_dana.csv")